# https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
name: Release Harmonizer
author: Aaron Csetter (aaron@csetter.com)
branding:
  icon: refresh-cw
  color: green
description: |
  After a release is creted, this action creates/updates branches and/or tags
  that point to the head commit of the new release. If you wish to include a
  version number in the new ref, the published release's tag must include a
  version number. For example, 'v1.2.3', '1.2.3', '2.1-beta', and
  'v2.1.3.6-alpha' are all acceptble tags to sync with.

inputs:
  github-token:
    default: ${{ github.token }}
    required: false
    description: |
      The GitHub token used to create an authenticated client.

  ref-type:
    required: true
    description: |
      ('tag' | 'branch') which type of ref to sync.

  sync-to:
    default: 'major'
    required: false
    description: |
      ('major' | 'minor' | 'patch' | 'full' | 'all') Determines how refs are
      synced with the release. For example, if 'major' is specified, versions
      starting at 1.0.0 and up to, but not including, 2.0.0 will be synced to
      the same ref. Versions higher than 2.0.0 will create a new ref. Default
      is 'major'.
       - 'major' syncs releases [1.0.0, 2.0.0) to the ref '<prefix>1<suffix>'
       - 'minor' syncs releases [1.1.0, 1.2.0) to the ref '<prefix>1.1<suffix>'
       - 'patch' syncs releases [2.0.1, 2.0.2) to the ref '<prefix>2.0.1<suffix>'
       - 'full' syncs release '1.2.3.4' to the ref '<prefix>1.2.3.4<suffix>'
       - 'all' syncs all releases to the ref '<prefix><suffix>'

  prefix:
    default: 'v'
    required: false
    description: |
      (string) The prefix for the ref-name. For example, the prefeix 'foo/bar'
      would produce branches 'foo/bar1', 'foo/bar2', and 'foo/bar3' when synced
      to major with a ref-type of 'branches'.

  suffix:
    default: ''
    required: false
    description: |
      (string) The suffix for the ref-name. For example, the suffix -latest
      would produce refs 'v1.0-latest', 'v1.1-latest', and 'v2.2-latest'
      when synced to minor with the prefix 'v'.

runs:
  using: composite
  steps:
    - name: Get script file path
      id: script-path
      shell: bash
      run: echo "path=${GITHUB_ACTION_PATH}/index.js" >> $GITHUB_OUTPUT
    
    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const script = require(`${{ steps.script-path.outputs.path }}`);
          script({
            github,
            context,
            core,
            inputs: {
              refType: `${{ inputs.ref-type }}`,
              syncTo: `${{ inputs.sync-to }}`,
              prefix: `${{ inputs.prefix }}`,
              suffix: `${{ inputs.suffix }}`,
            }
          });
