name: 🏷️ Sync Refs

on:
  release:
    types: 
      - published 

jobs:
  harmonizer:
    name: 🔃 Run Harmonizer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - ref-type: tag
            sync-to: major
            prefix: v
          - ref-type: branch
            sync-to: major
            prefix: releases/v
    steps:
      - name: 🗃️ Checkout
        uses: actions/checkout@v3

      - name: 🔃 Sync Tag
        uses: ./
        with:
          github-token: ${{ secrets.CI_SEMANTIC_RELEASE }}
          ref-type: ${{ matrix.ref-type }}
          sync-to: ${{ matrix.sync-to }}
          prefix: ${{ matrix.prefix }}
