name: 🏷️ Sync Refs

on:
  release:
    types: 
      - published 

jobs:
  sync-refs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        #? https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
        include:
          - ref-type: tag
            sync-to: minor
            prefix: v
            suffix: -beta
          - ref-type: branch
            sync-to: patch
            prefix: releases/v
            suffix: -beta
    steps:
      - name: 🗃️ Checkout
        uses: actions/checkout@v3

      - name: 🔃 Run Harmonizer
        uses: ./
        with:
          github-token: ${{ secrets.CI_SEMANTIC_RELEASE }}
          ref-type: ${{ matrix.ref-type }}
          sync-to: major
          prefix: ${{ matrix.prefix }}
